sudo: false

language: python

python:
  - 2.7
  - 3.4

cache:
  directories:
    - .

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION 
  - conda install --yes -c vxgmichel tango=9.2.2
  - conda install --yes numpy  # Not a strong requirement yet

script:
  - python setup.py test
