sudo: false

language: python

os: linux

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda create --yes --name buildenv python=$TRAVIS_PYTHON_VERSION
  - source activate buildenv
  - conda install --yes boost
  - conda install --yes -c vxgmichel tango=9.2.2
  - conda install --yes numpy  # Not a strong requirement yet
  - export BOOST_ROOT=$CONDA_PREFIX TANGO_ROOT=$CONDA_PREFIX ZMQ_ROOT=$CONDA_PREFIX OMNI_ROOT=$CONDA_PREFIX

script:
  - python setup.py test
